<script setup lang="ts">
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { api, APIError } from '@/api/client'
import { useAuthStore } from '@/stores/auth'
const auth = useAuthStore(); const router = useRouter(); const currentPassword=ref(''); const newPassword=ref(''); const confirmPassword=ref(''); const busy=ref(false); const error=ref<string|null>(null); const success=ref<string|null>(null)
async function changePassword(){error.value=null;success.value=null;if(newPassword.value!==confirmPassword.value){error.value='两次输入的新密码不一致。';return}busy.value=true;try{await api.auth.changePassword(currentPassword.value,newPassword.value,confirmPassword.value);currentPassword.value='';newPassword.value='';confirmPassword.value='';success.value='密码已修改，其他登录会话已撤销。'}catch(value){error.value=value instanceof APIError?value.message:'修改密码失败。'}finally{busy.value=false}}
async function logout(){await auth.logout();await router.replace('/login')}
</script>
<template><div class="simple-page"><p class="eyebrow">ACCOUNT</p><h1>我的账号</h1><section class="section-block prose-card"><h2>当前账号</h2><p><strong>{{ auth.user?.displayName || auth.user?.characterName || auth.user?.username || auth.user?.steamId }}</strong><br>{{ auth.user?.role==='admin'?'管理员':'玩家' }} · {{ auth.user?.status }}</p><p v-if="auth.user?.steamId"><small>SteamID64：{{ auth.user.steamId }}<br>角色：{{ auth.user.characterName }}</small></p><RouterLink v-if="auth.isAdmin" class="text-link" to="/admin/users">管理用户 →</RouterLink></section><section class="section-block prose-card"><h2>修改密码</h2><form class="auth-form" @submit.prevent="changePassword"><label>当前密码<input v-model="currentPassword" type="password" autocomplete="current-password" required /></label><label>新密码<input v-model="newPassword" type="password" autocomplete="new-password" minlength="8" maxlength="128" required /></label><label>确认新密码<input v-model="confirmPassword" type="password" autocomplete="new-password" minlength="8" maxlength="128" required /></label><div v-if="error" class="notice danger">{{ error }}</div><div v-if="success" class="notice success">{{ success }}</div><button class="primary-button" :disabled="busy">保存新密码</button></form></section><button class="secondary-button" type="button" @click="logout">退出登录</button><p class="account-version">Palworld Companion 0.4.2-dev</p></div></template>
