<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { api, APIError } from '@/api/client'
import type { User, UserStatus } from '@/types/auth'
const users=ref<User[]>([]); const filter=ref<UserStatus|''>(''); const error=ref<string|null>(null); const busy=ref(false); const resetID=ref<number|null>(null); const resetPassword=ref(''); const resetConfirm=ref('')
const labels:Record<string,string>={pending:'待审批',active:'正常',disabled:'已禁用',rejected:'已拒绝',deleted:'已删除',admin:'管理员',player:'玩家'}
const format=(value:string|null|undefined)=>value?new Date(value).toLocaleString():'—'
async function load(){error.value=null;try{users.value=(await api.admin.users(filter.value)).users}catch(value){error.value=value instanceof APIError?value.message:'加载失败'}}
async function action(user:User,name:'approve'|'disable'|'enable'|'restore'|'revoke-sessions'|'delete') { if(name==='delete'&&!confirm(`确认软删除 ${user.displayName||user.characterName||user.username||user.steamId}？`))return;busy.value=true;error.value=null;try{if(name==='delete')await api.admin.remove(user.id);else await api.admin.action(user.id,name);await load()}catch(value){error.value=value instanceof APIError?value.message:'操作失败'}finally{busy.value=false} }
async function reject(user:User){const reason=prompt('拒绝原因（可留空）','');if(reason===null)return;busy.value=true;try{await api.admin.reject(user.id,reason);await load()}catch(value){error.value=value instanceof APIError?value.message:'拒绝失败'}finally{busy.value=false}}
async function role(user:User){const next=user.role==='admin'?'player':'admin';if(!confirm(`确认将账号角色改为 ${labels[next]}？`))return;busy.value=true;try{await api.admin.setRole(user.id,next);await load()}catch(value){error.value=value instanceof APIError?value.message:'角色修改失败'}finally{busy.value=false}}
function beginReset(user:User){resetID.value=user.id;resetPassword.value='';resetConfirm.value=''}
async function submitReset(user:User){error.value=null;if(resetPassword.value!==resetConfirm.value){error.value='两次密码不一致。';return}busy.value=true;try{await api.admin.resetPassword(user.id,resetPassword.value,resetConfirm.value);resetID.value=null;resetPassword.value='';resetConfirm.value='';await load()}catch(value){error.value=value instanceof APIError?value.message:'密码重置失败'}finally{busy.value=false}}
onMounted(load)
</script>
<template><div class="simple-page"><p class="eyebrow">ADMIN</p><h1>用户管理</h1><label class="filter-label">状态筛选<select v-model="filter" @change="load"><option value="">全部</option><option value="pending">待审批</option><option value="active">正常</option><option value="disabled">已禁用</option><option value="rejected">已拒绝</option><option value="deleted">已删除</option></select></label><div v-if="error" class="notice danger">{{ error }}</div><section class="user-list"><article v-for="user in users" :key="user.id" class="prose-card user-card"><div><strong>{{ user.displayName || user.characterName || user.username || user.steamId }}</strong><p>{{ user.username || '无用户名' }} · {{ labels[user.role] }} · {{ labels[user.status] }}</p><small>角色名：{{ user.characterName || '—' }}<br>SteamID64：{{ user.steamId || '—' }}<br>Palworld userId：{{ user.palworldUserId || '—' }}<br>申请：{{ format(user.createdAt) }}<br>批准：{{ format(user.approvedAt) }}<br>最后登录：{{ format(user.lastLoginAt) }}<br>最后在线：{{ format(user.lastSeenAt) }}<template v-if="user.rejectionReason"><br>拒绝原因：{{ user.rejectionReason }}</template></small></div><div class="user-actions"><button v-if="user.status==='pending'||user.status==='rejected'" :disabled="busy" @click="action(user,'approve')">批准</button><button v-if="user.status==='pending'" :disabled="busy" @click="reject(user)">拒绝</button><button v-if="user.status==='active'" :disabled="busy" @click="action(user,'disable')">禁用</button><button v-if="user.status==='disabled'" :disabled="busy" @click="action(user,'enable')">启用</button><button v-if="user.status==='deleted'" :disabled="busy" @click="action(user,'restore')">恢复</button><button v-if="user.status!=='deleted'" :disabled="busy" @click="action(user,'delete')">软删除</button><button :disabled="busy" @click="role(user)">设为{{ user.role==='admin'?'玩家':'管理员' }}</button><button :disabled="busy" @click="beginReset(user)">重置密码</button><button :disabled="busy" @click="action(user,'revoke-sessions')">撤销会话</button></div><form v-if="resetID===user.id" class="reset-form" @submit.prevent="submitReset(user)"><label>新密码<input v-model="resetPassword" type="password" minlength="8" maxlength="128" required /></label><label>确认密码<input v-model="resetConfirm" type="password" minlength="8" maxlength="128" required /></label><button class="primary-button" :disabled="busy">确认重置并撤销会话</button><button type="button" class="text-button" @click="resetID=null">取消</button></form></article></section></div></template>
